### ISSUE TITLE
Android播放器初始化画面拉伸，旋转屏幕后恢复正常

### ISSUE THREAD

**Issue by mygu** [buhe/react-native-pili#10]
![android_player_issue](https://cloud.githubusercontent.com/assets/3753924/16070264/b99b4972-3306-11e6-9ee5-6ff27b25d4e7.png)

**Comment by mygu** [comment]
@buhe 还是上次issue #9 ，我copy你的demo，还是一样的问题，但是这次我发现如果把手机画面旋转后在旋转回来，就可以回复正常的全屏显示了，所以我感觉这是一个bug，你有空帮忙看一下，thanks~

**Comment by buhe** [comment]
好的。我尽快看一下。 这个和推流的分辨率也有关系。能告诉我推流分辨率么？

**Comment by buhe** [comment]
我自己手机测试了一下。 可以全屏但是确实有拉伸的问题。 当时预判和分辨率有关。我统一一下分辨率再试一下。
我用的是坚果手机。不过我估计这个和手机关系不大~
目前还不支持 设置分辨率。这几天加上去吧
另外，npm 推送出了点问题，还没搞。所以确定你用了 master 分支的代码是吧？

**Comment by mygu** [comment]
@buhe 我觉得应该不是手机的问题，我测试了2个手机都是这样的。我npm install都是master的～

**Comment by buhe** [comment]
这是个bug 已经改过来了
