### ISSUE TITLE
Android切换画面比例失败

### ISSUE THREAD

**Issue by mygu** [buhe/react-native-pili#12]
绑定属性：`aspectRatio={this.state.aspectRatio}`
然后有一个按钮点击触发事件修改state的值：`this.setState({aspectRatio: 1})`
但是这样并不能让页面重新渲染，导致画面大小没办法切换。

**Comment by buhe** [comment]
恩，我看一下

**Comment by buhe** [comment]
这个没有问题了吧，我先 close 了
