### ISSUE TITLE
[Android] Streaming推流闪退问题

### ISSUE THREAD

**Issue by mygu** [buhe/react-native-pili#13]
使用Streaming推流，第一次没有问题，但是返回上一级页面，第二次再次进入推流页面的时候就闪退了，以下是log信息。

![2016-07-11 16 59 59](https://cloud.githubusercontent.com/assets/3753924/16725520/2f7abf28-478a-11e6-9177-7223daa59b1c.png)

**Comment by buhe** [comment]
好的，我会尽快处理

**Comment by Zwem** [comment]
Have you any updates about this issue?

**Comment by buhe** [comment]
Move to github.com/react-native-piliv2
