### ISSUE TITLE
Native component for "RCTStreaming" does not exist

### ISSUE THREAD

**Issue by laoqiu** [buhe/react-native-pili#15]
能编译成功，但只有个空的红框，后台报了这个错误，我感觉像是没有安装好。
按你文档安装的，不知道哪里不对！求解

**Comment by laoqiu** [comment]
你的RCTPili.xcodeproj需要在Librariesg下面还是要在项目根目录上的？有特殊要求吗？

**Comment by buhe** [comment]
没有特殊要求，严格按照顺序来做就可以了

**Comment by laoqiu** [comment]
我发现跟你github上内容不一致，我试着用clone一个试下

**Comment by laoqiu** [comment]
ld: symbol(s) not found for architecture arm64
用github版本，编译就直接不过了。google了一遍，没有统一的说法，是你的静态库不支持arm64?
