### ISSUE TITLE
ios中streaming功能报参数为空错误

### ISSUE THREAD

**Issue by laoqiu** [buhe/react-native-pili#17]
2016-08-02 15:54:22.222 mylive_pili[620:245546] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSPlaceholderString initWithString:]: nil argument'
*** First throw call stack:
(0x182a0adb0 0x18206ff80 0x182a0acf8 0x183312bbc 0x183318e34 0x1000c675c 0x1000c89e4 0x1000c86f0 0x10004f3d4 0x1000332b0 0x100869a7c 0x100869a3c 0x100876554 0x10086d72c 0x100869a3c 0x100878c9c 0x100878364 0x18266d470 0x18266d020)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by laoqiu** [comment]
代码为github上clone的，已成功运行，但这个错误实在没头绪

**Comment by buhe** [comment]
好，我看一下

**Comment by buhe** [comment]
错误的信息太少了。你还依赖了什么 native 的 lib 么

**Comment by laoqiu** [comment]
没有加任何其他东西，只装了react-native-pili，也没有安装其他包

**Comment by laoqiu** [comment]
理论上，在stream中如果你某个参数是需要的，但你js中没有传过去，或是预期是不为空时，值空了，就会报这个错误

**Comment by buhe** [comment]
会从 JS 层进行约束，required 的如果不传，JS 会直接报错的。

**Comment by laoqiu** [comment]
我发现有如下这些警告，不知道是不是跟错误有关，能再帮分析一下吗？

while processing /Users/laoqiu/Library/Developer/Xcode/DerivedData/mylive_pili-cuiaqetdhyuvebdpfpwgqzgbtpvq/Build/Products/Debug-iphoneos/libRCTPili.a(PLMediaFrame.o):
warning: /var/folders/r4/0d8v6kwj45x_s9qfbdyc8qgr0000gn/C/org.llvm.clang.wangsiyu/ModuleCache/13P5ICTU9MNN1/Foundation-A3SOD99KJ0S9.pcm: No such file or directory
note: Module debugging should be disabled when shipping static libraries.
while processing /Users/laoqiu/Library/Developer/Xcode/DerivedData/mylive_pili-cuiaqetdhyuvebdpfpwgqzgbtpvq/Build/Products/Debug-iphoneos/libRCTPili.a(PLMediaFrame.o):
warning: /var/folders/r4/0d8v6kwj45x_s9qfbdyc8qgr0000gn/C/org.llvm.clang.wangsiyu/ModuleCache/13P5ICTU9MNN1/ObjectiveC-2CD0WTQVXITO7.pcm: No such file or directory
while processing /Users/laoqiu/Library/Developer/Xcode/DerivedData/mylive_pili-cuiaqetdhyuvebdpfpwgqzgbtpvq/Build/Products/Debug-iphoneos/libRCTPili.a(PLRTMPContext.o):
warning: /var/folders/r4/0d8v6kwj45x_s9qfbdyc8qgr0000gn/C/org.llvm.clang.wangsiyu/ModuleCache/13P5ICTU9MNN1/UIKit-2LM3EQU7VVY4O.pcm: No such file or directory
while processing /Users/laoqiu/Library/Developer/Xcode/DerivedData/mylive_pili-cuiaqetdhyuvebdpfpwgqzgbtpvq/Build/Products/Debug-iphoneos/libRCTPili.a(PLRTMPContext.o):
warning: /var/folders/r4/0d8v6kwj45x_s9qfbdyc8qgr0000gn/C/org.llvm.clang.wangsiyu/ModuleCache/13P5ICTU9MNN1/CoreMedia-GG7O0RHFFJKF.pcm: No such file or directory
while processing /Users/laoqiu/Library/Developer/Xcode/DerivedData/mylive_pili-cuiaqetdhyuvebdpfpwgqzgbtpvq/Build/Products/Debug-iphoneos/libRCTPili.a(PLRTMPContext.o):
warning: /var/folders/r4/0d8v6kwj45x_s9qfbdyc8qgr0000gn/C/org.llvm.clang.wangsiyu/ModuleCache/13P5ICTU9MNN1/AudioToolbox-IDGAMJDSP9Z1.pcm: No such file or directory
while processing /Users/laoqiu/Library/Developer/Xcode/DerivedData/mylive_pili-cuiaqetdhyuvebdpfpwgqzgbtpvq/Build/Products/Debug-iphoneos/libRCTPili.a(PLRTMPContext.o):
warning: /var/folders/r4/0d8v6kwj45x_s9qfbdyc8qgr0000gn/C/org.llvm.clang.wangsiyu/ModuleCache/13P5ICTU9MNN1/CoreAudio-X7XIL788GQ9E.pcm: No such file or directory
while processing /Users/laoqiu/Library/Developer/Xcode/DerivedData/mylive_pili-cuiaqetdhyuvebdpfpwgqzgbtpvq/Build/Products/Debug-iphoneos/libRCTPili.a(PLRTMPContext.o):
warning: /var/folders/r4/0d8v6kwj45x_s9qfbdyc8qgr0000gn/C/org.llvm.clang.wangsiyu/ModuleCache/13P5ICTU9MNN1/CoreAudioKit-BNSCCXRZYE5Q.pcm: No such file or directory
while processing /Users/laoqiu/Library/Developer/Xcode/DerivedData/mylive_pili-cuiaqetdhyuvebdpfpwgqzgbtpvq/Build/Products/Debug-iphoneos/libRCTPili.a(PLRTMPContext.o):
warning: /var/folders/r4/0d8v6kwj45x_s9qfbdyc8qgr0000gn/C/org.llvm.clang.wangsiyu/ModuleCache/13P5ICTU9MNN1/AVFoundation-7O317LEIB4Z2.pcm: No such file or directory
while processing /Users/laoqiu/Library/Developer/Xcode/DerivedData/mylive_pili-cuiaqetdhyuvebdpfpwgqzgbtpvq/Build/Products/Debug-iphoneos/libRCTPili.a(PLRTMPContext.o):
warning: /var/folders/r4/0d8v6kwj45x_s9qfbdyc8qgr0000gn/C/org.llvm.clang.wangsiyu/ModuleCache/13P5ICTU9MNN1/Darwin-MI6WZSG1PNOM.pcm: No such file or directory
while processing /Users/laoqiu/Library/Developer/Xcode/DerivedData/mylive_pili-cuiaqetdhyuvebdpfpwgqzgbtpvq/Build/Products/Debug-iphoneos/libRCTPili.a(PLRTMPContext.o):
warning: /var/folders/r4/0d8v6kwj45x_s9qfbdyc8qgr0000gn/C/org.llvm.clang.wangsiyu/ModuleCache/13P5ICTU9MNN1/CoreFoundation-10I2D2XL7L7X9.pcm: No such file or directory
while processing /Users/laoqiu/Library/Developer/Xcode/DerivedData/mylive_pili-cuiaqetdhyuvebdpfpwgqzgbtpvq/Build/Products/Debug-iphoneos/libRCTPili.a(PLGLView.o):
warning: /var/folders/r4/0d8v6kwj45x_s9qfbdyc8qgr0000gn/C/org.llvm.clang.wangsiyu/ModuleCache/13P5ICTU9MNN1/OpenGLES-1739WO7XX8M93.pcm: No such file or directory
while processing /Users/laoqiu/Library/Developer/Xcode/DerivedData/mylive_pili-cuiaqetdhyuvebdpfpwgqzgbtpvq/Build/Products/Debug-iphoneos/libRCTPili.a(PLGLView.o):
warning: /var/folders/r4/0d8v6kwj45x_s9qfbdyc8qgr0000gn/C/org.llvm.clang.wangsiyu/ModuleCache/13P5ICTU9MNN1/CoreGraphics-1YQ59ILDR3NYI.pcm: No such file or directory
while processing /Users/laoqiu/Library/Developer/Xcode/DerivedData/mylive_pili-cuiaqetdhyuvebdpfpwgqzgbtpvq/Build/Products/Debug-iphoneos/libRCTPili.a(PLGLView.o):
warning: /var/folders/r4/0d8v6kwj45x_s9qfbdyc8qgr0000gn/C/org.llvm.clang.wangsiyu/ModuleCache/13P5ICTU9MNN1/QuartzCore-3I7S0M4UEAD0U.pcm: No such file or directory
while processing /Users/laoqiu/Library/Developer/Xcode/DerivedData/mylive_pili-cuiaqetdhyuvebdpfpwgqzgbtpvq/Build/Products/Debug-iphoneos/libRCTPili.a(PLPlayerUtilsFunctions.o):
warning: /var/folders/r4/0d8v6kwj45x_s9qfbdyc8qgr0000gn/C/org.llvm.clang.wangsiyu/ModuleCache/1227FI1D5PK1X/Darwin-MI6WZSG1PNOM.pcm: No such file or directory
while processing /Users/laoqiu/Library/Developer/Xcode/DerivedData/mylive_pili-cuiaqetdhyuvebdpfpwgqzgbtpvq/Build/Products/Debug-iphoneos/libRCTPili.a(PLPlayerUtilsFunctions.o):
warning: /var/folders/r4/0d8v6kwj45x_s9qfbdyc8qgr0000gn/C/org.llvm.clang.wangsiyu/ModuleCache/1227FI1D5PK1X/CoreFoundation-10I2D2XL7L7X9.pcm: No such file or directory
while processing /Users/laoqiu/Library/Developer/Xcode/DerivedData/mylive_pili-cuiaqetdhyuvebdpfpwgqzgbtpvq/Build/Products/Debug-iphoneos/libRCTPili.a(PLPlayerUtilsFunctions.o):
warning: /var/folders/r4/0d8v6kwj45x_s9qfbdyc8qgr0000gn/C/org.llvm.clang.wangsiyu/ModuleCache/1227FI1D5PK1X/CoreAudio-X7XIL788GQ9E.pcm: No such file or directory
while processing /Users/laoqiu/Library/Developer/Xcode/DerivedData/mylive_pili-cuiaqetdhyuvebdpfpwgqzgbtpvq/Build/Products/Debug-iphoneos/libRCTPili.a(PLPlayerUtilsFunctions.o):
warning: /var/folders/r4/0d8v6kwj45x_s9qfbdyc8qgr0000gn/C/org.llvm.clang.wangsiyu/ModuleCache/1227FI1D5PK1X/Dispatch-12O7S7HHQXK9N.pcm: No such file or directory

**Comment by laoqiu** [comment]
加了断点，发现错误代码是在这行
                // 推流 session
                self.session = [[PLCameraStreamingSession alloc] initWithVideoCaptureConfiguration:videoCaptureConfiguration audioCaptureConfiguration:audioCaptureConfiguration videoStreamingConfiguration:videoStreamingConfiguration audioStreamingConfiguration:audioStreamingConfiguration stream:stream videoOrientation:orientation];

**Comment by buhe** [comment]
这行直接 crash 了？你的推流地址是 自己申请的么？

**Comment by laoqiu** [comment]
是你们七牛的推流地址啊，用sdk通过stream.to_json出来的地址

**Comment by laoqiu** [comment]
确定是在那一行，但再深入PLCameraStreamingSession，我不知道应该怎么加断点了，都是方法

**Comment by pj0579** [comment]
我也clone下来这个,安装不成功，请问你的是怎么安装成功的

**Comment by pj0579** [comment]
error: can't open file: /Users/usr/lib/libresolv.9.dylib (No such file or directory) 这个东西有

**Comment by laoqiu** [comment]
你libresolv.9.dylib这个库的地址可能错了
运行成功也没用啊，根本跑不了。

**Comment by pj0579** [comment]
你的现在成功跑起来了吗？我的还是不行

**Comment by pj0579** [comment]
ld: embedded dylibs/frameworks are only supported on iOS 8.0 and later (@rpath/GPUImage.framework/GPUImage) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)现在是这个错误

**Comment by pj0579** [comment]
刚才错误贴错了"_res_9_ndestroy", referenced from:
      _query_ip_v4 in libRCTPili.a(QNResolver.o)
      _query_ip_v6 in libRCTPili.a(QNResolver.o)
      _query_ip in libRCTPili.a(QNTxtResolver.o)
  "_res_9_ninit", referenced from:
      _setup_dns_server in libRCTPili.a(QNResolver.o)
      _setup_dns_server in libRCTPili.a(QNTxtResolver.o)
  "_res_9_nquery", referenced from:
      _query_ip_v4 in libRCTPili.a(QNResolver.o)
      _query_ip_v6 in libRCTPili.a(QNResolver.o)
      _query_ip in libRCTPili.a(QNTxtResolver.o)
  "_res_9_ns_initparse", referenced from:
      _query_ip_v4 in libRCTPili.a(QNResolver.o)
      _query_ip_v6 in libRCTPili.a(QNResolver.o)
      _query_ip in libRCTPili.a(QNTxtResolver.o)
  "_res_9_ns_name_uncompress", referenced from:
      _query_ip_v4 in libRCTPili.a(QNResolver.o)
      _query_ip_v6 in libRCTPili.a(QNResolver.o)
  "_res_9_ns_parserr", referenced from:
      _query_ip_v4 in libRCTPili.a(QNResolver.o)
      _query_ip_v6 in libRCTPili.a(QNResolver.o)
      _query_ip in libRCTPili.a(QNTxtResolver.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by pj0579** [comment]
突然发现我的这个问题应该与你的是一样的，请问你的是怎么解决的

**Comment by laoqiu** [comment]
你这个问题，是包依赖的问题，你要点开pili的包，看看里面的path对不对。理论上是不对的，你要改成你本地的

**Comment by pj0579** [comment]
pili的包path 具体改什么地方？

**Comment by laoqiu** [comment]
在根项目中需要用到libresolv.tbd和libz.1.2.5.tbd
在RCTPili.xcodeproj中，看看Header Search Paths和Library Search Paths这两个是不是对的

**Comment by pj0579** [comment]
可以加个QQ聊吗

**Comment by laoqiu** [comment]
微信号laoqiu84

**Comment by pj0579** [comment]
好的

**Comment by buhe** [comment]
same as #18
