### ISSUE TITLE
ios Streaming运行闪退，希望大神有空改进

### ISSUE THREAD

**Issue by pj0579** [buhe/react-native-pili#18]
Test[11761:556098] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSPlaceholderString initWithString:]: nil argument'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001084f8d85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x00000001073e0deb objc_exception_throw + 48
	2   CoreFoundation                      0x00000001084f8cbd +[NSException raise:format:] + 205
	3   Foundation                          0x0000000106fcdf39 -[NSPlaceholderString initWithString:] + 96
	4   Foundation                          0x0000000106f83501 +[NSString stringWithString:] + 45
	5   Test                                0x000000010693e057 -[PLStreamingSession(QoS) postAppLauchInfo] + 162
	6   Test                                0x0000000106940498 -[PLStreamingSession initWithVideoStreamingConfiguration:audioStreamingConfiguration:stream:dns:] + 545
	7   Test                                0x00000001069401c2 -[PLStreamingSession initWithVideoStreamingConfiguration:audioStreamingConfiguration:stream:] + 74
	8   Test                                0x00000001068ccbdb -[PLCameraStreamingSession initWithVideoCaptureConfiguration:audioCaptureConfiguration:videoStreamingConfiguration:audioStreamingConfiguration:stream:videoOrientation:] + 491
	9   Test                                0x00000001068b0fe8 __35-[RCTStreaming setSourceAndProfile]_block_invoke_2 + 1208
	10  libdispatch.dylib                   0x000000010bf08d9d _dispatch_call_block_and_release + 12
	11  libdispatch.dylib                   0x000000010bf293eb _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x000000010bf0f82c _dispatch_queue_drain + 2215
	13  libdispatch.dylib                   0x000000010bf0ed4d _dispatch_queue_invoke + 601
	14  libdispatch.dylib                   0x000000010bf11996 _dispatch_root_queue_drain + 1420
	15  libdispatch.dylib                   0x000000010bf11405 _dispatch_worker_thread3 + 111
	16  libsystem_pthread.dylib             0x000000010c2664de _pthread_wqthread + 1129
	17  libsystem_pthread.dylib             0x000000010c264341 start_wqthread + 13
)

**Comment by pj0579** [comment]
推流一切配置正确还是，无法获取摄像头预览页面，然后直接闪退

**Comment by pj0579** [comment]
2016-08-29 15:18:18.392 WeidaoApp[46779:351680] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSLayoutConstraint constraintWithItem:attribute:relatedBy:toItem:attribute:multiplier:constant:]: Constraint must contain a first layout item'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000106340d85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x00000001050f3deb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000106340cbd +[NSException raise:format:] + 205
	3   Foundation                          0x0000000104cba09e +[NSLayoutConstraint constraintWithItem:attribute:relatedBy:toItem:attribute:multiplier:constant:] + 263
	4   WeidaoApp                           0x00000001040505d3 __35-[RCTStreaming setSourceAndProfile]_block_invoke_3 + 227
	5   libdispatch.dylib                   0x000000010a034d9d _dispatch_call_block_and_release + 12
	6   libdispatch.dylib                   0x000000010a0553eb _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x000000010a03d1ef _dispatch_main_queue_callback_4CF + 1738
	8   CoreFoundation                      0x000000010629a0f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	9   CoreFoundation                      0x000000010625bb99 __CFRunLoopRun + 2073
	10  CoreFoundation                      0x000000010625b0f8 CFRunLoopRunSpecific + 488
	11  GraphicsServices                    0x000000010aac0ad2 GSEventRunModal + 161
	12  UIKit                               0x0000000108648f09 UIApplicationMain + 171
	13  WeidaoApp                           0x000000010404b80f main + 111
	14  libdyld.dylib                       0x000000010a08992d start + 1
	15  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

预览界面 preview  一直是空的

**Comment by buhe** [comment]
我准备升级到 pili 2.x 版本，现在 pili 本身版本迭代太快，没办法很好的跟进

**Comment by pj0579** [comment]
那这个闪退有办法解决吗

**Comment by pj0579** [comment]
预览对象 一直为nil

**Comment by pj0579** [comment]
请问您的react-native-pili 现在ios推流端可以正常运行吗？

**Comment by buhe** [comment]
我自己都测试过，是没有问题的。 你可以直接 checkout pilipili 这个项目看一下，看看有没有帮助。

**Comment by pj0579** [comment]
android 没有问题 就是ios的一直闪退

**Comment by pj0579** [comment]
你的pilipili项目可以直接运行吗？

**Comment by pj0579** [comment]
npm install 依赖库无法下载

**Comment by pj0579** [comment]
可以加个什么聊一下吗

**Comment by buhe** [comment]
1. 去掉 react-native-pili 的相对路径的依赖，直接 npm install
2. 把 react-native-pili 项目 clone 过去，然后把相对路径配置好

**Comment by pj0579** [comment]
我估计错在这相对路径，react-native-pili 项目的相对路径怎么配置，我先前都是直接clone下来，然后配置库就完了

**Comment by buhe** [comment]
恩，你的做法是对的。 
先删除掉，再加回去。 现在 package.json 里面如果有相对路径 install 会出错的。

**Comment by pj0579** [comment]
clang: error: no such file or directory: '/Users/xukankan/Library/Developer/Xcode/DerivedData/pilipili-cqfgkkjoonnlvsgjbyngnxysatpa/Build/Products/Debug-iphonesimulator/libRCTPili.a'
clang: error: no such file or directory: '/Users/xukankan/Library/Developer/Xcode/DerivedData/pilipili-cqfgkkjoonnlvsgjbyngnxysatpa/Build/Products/Debug-iphonesimulator/libReact.a'
clang: error: no such file or directory: '/Users/xukankan/Library/Developer/Xcode/DerivedData/pilipili-cqfgkkjoonnlvsgjbyngnxysatpa/Build/Products/Debug-iphonesimulator/libRCTActionSheet.a'
clang: error: no such file or directory: '/Users/xukankan/Library/Developer/Xcode/DerivedData/pilipili-cqfgkkjoonnlvsgjbyngnxysatpa/Build/Products/Debug-iphonesimulator/libRCTGeolocation.a'
clang: error: no such file or directory: '/Users/xukankan/Library/Developer/Xcode/DerivedData/pilipili-cqfgkkjoonnlvsgjbyngnxysatpa/Build/Products/Debug-iphonesimulator/libRCTImage.a'
clang: error: no such file or directory: '/Users/xukankan/Library/Developer/Xcode/DerivedData/pilipili-cqfgkkjoonnlvsgjbyngnxysatpa/Build/Products/Debug-iphonesimulator/libRCTLinking.a'
clang: error: no such file or directory: '/Users/xukankan/Library/Developer/Xcode/DerivedData/pilipili-cqfgkkjoonnlvsgjbyngnxysatpa/Build/Products/Debug-iphonesimulator/libRCTNetwork.a'
clang: error: no such file or directory: '/Users/xukankan/Library/Developer/Xcode/DerivedData/pilipili-cqfgkkjoonnlvsgjbyngnxysatpa/Build/Products/Debug-iphonesimulator/libRCTSettings.a'
clang: error: no such file or directory: '/Users/xukankan/Library/Developer/Xcode/DerivedData/pilipili-cqfgkkjoonnlvsgjbyngnxysatpa/Build/Products/Debug-iphonesimulator/libRCTText.a'
clang: error: no such file or directory: '/Users/xukankan/Library/Developer/Xcode/DerivedData/pilipili-cqfgkkjoonnlvsgjbyngnxysatpa/Build/Products/Debug-iphonesimulator/libRCTVibration.a'
clang: error: no such file or directory: '/Users/xukankan/Library/Developer/Xcode/DerivedData/pilipili-cqfgkkjoonnlvsgjbyngnxysatpa/Build/Products/Debug-iphonesimulator/libRCTWebSocket.a'
运行pili项目出现这些错误

**Comment by pj0579** [comment]
为什么缓存会出现问题

**Comment by pj0579** [comment]
运行pilipili Demo还是报相同的错误，ios端推流依旧不行

**Comment by pj0579** [comment]
{
    hosts =     {
        publish =         {
            rtmp = "pili-publish.pilitest.qiniucdn.com";
        };
    };
    hub = pilitest;
    id = buhe;
    publishKey = 6eeee8a82246636e;
    publishSecurity = static;
    title = buhe;
}
你的Demo 这个推流JSON有没有问题

**Comment by pj0579** [comment]
dispatch_async(dispatch_get_main_queue(), ^{
                    UIView *previewView = self.session.previewView;
                    [self addSubview:previewView];
                    [previewView setTranslatesAutoresizingMaskIntoConstraints:NO];
                    if(self.session.previewView==nil){
                        NSLog(@"预览界面为空");
                    }
                    NSLayoutConstraint *centerX = [NSLayoutConstraint constraintWithItem:previewView attribute:NSLayoutAttributeCenterX relatedBy:NSLayoutRelationEqual toItem:self attribute:NSLayoutAttributeCenterX multiplier:1.0 constant:0];

2016-08-30 16:18:41.245 pilipili[84384:378020] 输出预览界面为空

运行到 NSLayoutConstraint *centerX = [NSLayoutConstraint constraintWithItem:previewView ，为空就crash了

**Comment by buhe** [comment]
这个json 是非法的。 用你自己的

**Comment by pj0579** [comment]
知道了

**Comment by pj0579** [comment]
可以先发我一个测试推流JSON 吗 我们想先测试一下 再连你们的服务

**Comment by pj0579** [comment]
突然想起来 Android推流用的也是这几个数据，为什么Android的可以正常运行

**Comment by pj0579** [comment]
json没问题，问题已解决

**Comment by pj0579** [comment]
谢谢耐心指导

**Comment by buhe** [comment]
抱歉没有更多时间回复，我要等到 pili 的 core sdk 稳定了，再去继续开发这个项目。目前迭代比较快，而且我自己也比较忙，实在没有太多精力。
