### ISSUE TITLE
iOS installation 

### ISSUE THREAD

**Issue by m-tbox** [buhe/react-native-pili#20]
I have used " npm install react-native-pili --save " but cannot find libPTCPili.a instead I have RCTPili.framework in my RCTPili.xcodeproj how can I use this to install react-native-pili in iOS ?

**Comment by buhe** [comment]
please use https://github.com/qiniu/react-native-piliv2
use cocoapods for iOS

**Comment by m-tbox** [comment]
@buhe I am unable to open this link.
I get an error that is "404: this is not the web page you are looking for."

**Comment by buhe** [comment]
sorry for late

https://github.com/buhe/react-native-piliv2 <https://github.com/buhe/react-native-piliv2>
