### ISSUE TITLE
Streaming to my rtmp server

### ISSUE THREAD

**Issue by ldima** [buhe/react-native-pili#3]
Hello friend. I want use  this library for steaming to my rtmp server. 
What is  key=6eeee8a82246636e" in url ?
Do i use you library for my rtmp server ?

**Comment by buhe** [comment]
Hey , the lib is pili streaming cloud sdk .this library can't steaming to other rtmp server for now.
But,we will cancel restriction in future.

Thanks

**Comment by ldima** [comment]
Friend please say me how cancel restriction and i do it now.

**Comment by buhe** [comment]
This is our website , http://www.qiniu.com/products/pili .
send email to sales@qiniu.com for detail .

Thanks
