### ISSUE TITLE
react-native run-android 编译报错

### ISSUE THREAD

**Issue by mygu** [buhe/react-native-pili#4]
Could not read script '/node_modules/react-native/react_forui.gradle' as it does not exist.

**Comment by buhe** [comment]
感谢反馈，稍后会解决

**Comment by buhe** [comment]
master 上已经 fix了 ，还没有发布到 npm 上面。 会等 issue #3  解决了一并发布。

**Comment by mygu** [comment]
@buhe Thanks，我回头来试一下~
