### ISSUE TITLE
Android报错闪退

### ISSUE THREAD

**Issue by mygu** [buhe/react-native-pili#6]
Fixed #4 ，现在react-native run-android编译正常通过，但是app报错闪退了。

我这边看不到报错信息，所以没办法定位问题。我怀疑是不是编译版本的问题，现在编译的SDK版本是23.0.1，我记得我编译官方demo的时候好像也报错了，降到22.0.1就work了，不知到这边是不是也是这个问题。我试图修改react-native的编译版本，但是失败了，你能看下是什么问题吗？Thanks~

**Comment by buhe** [comment]
Sorry for later. 我回复邮件给你了，可以打电话或者 wechat 找我。我先把 bug2 fix了，之后会尝试复现一下你这个问题。
如果有什么新的发现，可以告诉我

**Comment by mygu** [comment]
@buhe 问题修复了，thanks for your time~ 

原因是grade的版本问题，我原来的竟然是1.3.1，真奇怪。编辑build.gradle里面
`classpath 'com.android.tools.build:gradle:1.3.1'`
改成
`classpath 'com.android.tools.build:gradle:2.1.0'`
