### ISSUE TITLE
画面预览模式

### ISSUE THREAD

**Issue by mygu** [buhe/react-native-pili#7]
我这边现在测试发现android player画面被拉伸了，如果下面写一个`<Text>`就没问题，会自动缩放，但是并不能铺满全屏。我看了官方demo的代码，有一个`mVideoView.setDisplayAspectRatio(mDisplayAspectRatio);`的方法，是不是我们这个版本现在没有？

**Comment by buhe** [comment]
谢谢反馈，估计要下周能看这个问题。
如果急 可以尝试先修复一下 :)

**Comment by mygu** [comment]
@buhe 我简单实现了切换画面预览模式的功能，已经提交了pull requests（#7）。缺少`<Text>`画面会被拉伸的问题，我重新开一个issue（#9）
